site:
  name: Prof. Dr. Alp Burak Çatakoğlu
  site: 'https://catakoglu.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: m-45yEao6rnJtWCBYp9KYJwu_SRv92hdmFm39onUOxA

# Default SEO metadata
metadata:
  title:
    default: Prof Dr Alp Burak Çatakoğlu
    template: '%s — Prof Dr Alp Burak Çatakoğlu'
  description: "Prof Dr Alp Burak Çatakoğlu resmi web sitesi. Koroner anjiyo ve stent, TAVİ, MitraClip, TriClip, ASD ve PFO kapatma, karotis stentleme ve renal denervasyon gibi ameliyatsız kalp tedavileri hakkında bilgi alabilirsiniz."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Prof. Dr. Alp Burak Çatakoğlu
    images:
      - url: '~/assets/images/alp_burak_catakoglu.png'
        width: 1200
        height: 630
    type: website
  twitter:
    handle: '@dralpburak'
    site: '@dralpburak'
    cardType: summary_large_image

i18n:
  language: tr
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: false
      pathname: 'makaleler' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: false

    category:
      isEnabled: true
      pathname: 'kategori' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: false

    tag:
      isEnabled: true
      pathname: 'etiket' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: "G-YD3XJJRTL7"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
